server:
  port: 8080
spring:
  datasource :
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pms_ui
    username: postgres
    password: Password@123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgresqlDialect